<?php

define("EXTENDED_MESSAGING_XMPP_DOMAIN", variable_get('extended_messaging_domain', $cookie_domain));
define("EXTENDED_MESSAGING_XMPP_SERVER", variable_get('extended_messaging_server', 'http://xmpp.asaoweb.com:5280/http-bind/'));
define("EXTENDED_MESSAGING_XMPP_PORT", variable_get('extended_messaging_port', '5222'));
define("EXTENDED_MESSAGING_XMPP_WS_URL", variable_get('extended_messaging_ws_url', 'ws://xmpp.asaoweb.com:5280/xmpp-websocket/'));
define("EXTENDED_MESSAGING_XMPP_PRICACY_MODE", variable_get('extended_messaging_privacy_mode', 'blacklist'));

function extended_messaging_menu() {
   $items = array();
     
   $items['messaging/rpc/%'] = array(
         'page callback' => 'extended_messaging_rpc',
         'page arguments' => array(2),
         'access arguments' => array('access content'),
         'file' => 'includes/extended_messaging.rpc.inc',
         'type' => MENU_CALLBACK,
   );
   
   //// ADMIN
   $items['admin/settings/extended_messaging'] = array(
         'title' => 'Extended Messaging',
         'description' => 'Global settings for extended messaging.',
         'page callback' => 'drupal_get_form',
         'page arguments' => array('extended_messaging_admin'),
         'access arguments' => array('admin'),
         'file' => 'includes/extended_messaging.admin.inc',
         'type' => MENU_NORMAL_ITEM
   );
    
   return $items;
}

function extended_messaging_include_settings($with=0) {
   static $current;
    
   // be sure we only add the setting only once
   if ( empty($current) ) {
      global $user;
            
      module_load_include('class.inc', 'extended_messaging', 'includes/classes/ExtendedMessagingUser');

      $xmpp = ExtendedMessagingUser::instance();
      
      $settings = array(
         'xmpp' => array(
               'server'   => EXTENDED_MESSAGING_XMPP_SERVER, 
               'ws'       => EXTENDED_MESSAGING_XMPP_WS_URL, 
               'port'     => EXTENDED_MESSAGING_XMPP_PORT, 
               'domain'   => EXTENDED_MESSAGING_XMPP_DOMAIN,
               'jid'      => $xmpp->BareJID(),
               'auth'     => $xmpp->Auth(),
               'nickname' => $xmpp->Nick(),
               'groups'   => array("groups" => array( 
                              array("xmppname"=>"Friends", "displayname"=>"Mes amis" ), 
			  )), 
        ),
         //'roles' => user_roles(true),
         'roles' => $user->roles,
         'rpcbase' => url('messaging/rpc/'),
         'debug' => variable_get('extended_messaging_debug', 0)
      );

      drupal_alter('em_roster_groups', $settings['xmpp']['groups']);
      $htmlcolumnurl = "";
      drupal_alter('em_html_url', $htmlcolumnurl);
      if (!empty($htmlcolumnurl)) {
        $settings['htmlcol'] = $htmlcolumnurl;
      }
      if ( is_object($with) && $with->uid > 0) {
        $settings['initwith'] = $with->uid;
      }
      drupal_alter('em_settings', $settings);

      $old_setting = drupal_add_js(array('extended_messaging' => $settings), 'setting');
      $current[] = $settings;
   }
}

function extended_messaging_cron() {
// clean old sessions
  $result = db_query('DELETE FROM {extended_messaging_sessions} WHERE created < UNIX_TIMESTAMP()-60');
}
